package ro.foodx.backend.model.store;

public enum StoreType {
    FASTFOOD, CAFENEA, LIBANEZ, GRECESC, TURCESC, INDIAN, ASIATIC, SUPERMARKET, ROMANESC, RESTAURANT, VEGAN, ITALIAN, AMERICAN, MAGHIAR, SARBESC
}
